userdata/default_instance_user_data.yaml
userdata/monitor_instance_user_data.yaml
userdata/persistent_instance_user_data.yaml

Now users a docker repo mirror service that caches images

Added docker conf for the docker deamon

---

aws_coreos_site.yml
userdata/default_instance_user_data.yaml

https://github.com/Financial-Times/up-service-files/pull/15

Create a new elb for a new cluster with id

---

aws_coreos_site.yml

First pass at vpc conf

---

ansible/aws_coreos_site.yml
ansible/userdata/default_instance_user_data.yaml
ansible/userdata/persistent_instance_user_data_1.yaml
ansible/userdata/persistent_instance_user_data_2.yaml
ansible/userdata/persistent_instance_user_data_3.yaml

Stop fleet for erroring all the time and alleviate cpu and memory
problems

Switch to m3 larges and add etcd2 legacy ports

---

ansible/aws_coreos_site.yml

Reflects the change we made in pre-prod

Increase data volumes to 200GB

---

ansible/userdata/default_instance_user_data.yaml

Effort for service healthcheck not flagging oneshot services

Deployer remain active after exit

---

ansible/userdata/default_instance_user_data.yaml

Now live with deployer application, smaller user data, easier to edit

Move out service files for deployer

---

ansible/aws_coreos_site.yml

Also added an extra node so there's one persistent and one stateless per AZ.

Run hosts in mulitple Availability Zones (a,b and c)

---

ACCESS_CLUSTER.md
CLEANUP-README.md
README.md
ansible/aws_coreos_site.yml
ansible/userdata/default_instance_user_data.yaml
ansible/userdata/persistent_instance_user_data.yaml
decom.sh
provision.sh

Reverts Financial-Times/coco-provisioner#77

Revert "Separated region from environment_tag as region_tag"

---

ssh-tun0

Copy/paste from usage function inside the script
USAGE: ssh-tun0 <username>@<hostname or ipaddress>
Script logic in nutshell:
- Check that argument was provided
- Resolve ip address belonging to target host
- Verify VPN tunnel interface is up
- Create ip route record for host via tunnel interface
- Establishes SSH session to given host
- On termination prompt whether to remove ip route record from routing table

ssh-tun0 helper script for SSH connectivity on Linux when working remotely

---

Dockerfile

Which in turn is required by ansible v2

Add packages required by cryptography

---

ansible/aws_coreos_site.yml

We are wasting entirely too much time dealing with images and disk
space. Create some contingency.

Increate root volume to 100G

---

provision.sh

- example output in LastPass, `provisioner-verbose-output` note
- not sure if it also outputs something when deleting instances, but might be useful

Making ansible output verbose

---

README.md
ansible/userdata/default_instance_user_data.yaml
provision.sh

this PR is related to this PR: https://github.com/Financial-Times/up-service-files/pull/615

added etcd entry for gateway host for read api

---

README.md

some more readme tidyup, this time for the decommissioning bits

updating decommissioning env vars in readme

---

README.md
cloudformation/README.md

Adding Table of Contents into README.md.
Add paragraph for Coco Management Server.

Readme toc

---

README.md
ansible/aws_coreos_site.yml

Prints the cluster tunnel address once provisioning is complete.
Requested by @jussi-ft .

Print cluster tunnel address

---

Dockerfile
README.md

Automagic builds in Docker Hub have been failing for a week or so.
Moving the `ADD` statements above the `RUN` statements fixes this (thanks @peteclark-ft!).

Docker Hub autobuild fix

---

README.md
ansible/aws_coreos_site.yml

Remove Martin Garton from IP whitelist

---

README.md
ansible/userdata/default_instance_user_data.yaml
provision.sh

SPLUNK_HEC_URL is optional, SPLUNK_HEC_TOKEN is mandatory variable. Value for SPLUNK_HEC_TOKEN is stored in LastPass

Introduce variables SPLUNK_HEC_URL and SPLUNK_HEC_TOKEN in provision.sh

---

ansible/decom.yml

Raise CRs when deleting DNS records as UPP, rather than me.

Update DNS email

---

DEVELOPER_README.md
README.md
ansible/userdata/default_instance_user_data.yaml
provision.sh

Tested with a newly created cluster
Goes with https://github.com/Financial-Times/up-service-files/pull/954

Adding methode-api host

---

DEVELOPER_README.md
README.md
ansible/userdata/default_instance_user_data.yaml
provision.sh

- updated lastpass setup notes with ES AWS endpoints for PROD and TEST
- the TEST version is for pre-prod, for team clusters please create a separate ES cluster - TODO how to create and populate it quickly 
- haven't actually run this, waiting to confirm there's nothing more to add

Added es aws endpoint

---

ansible/userdata/default_instance_user_data.yaml
ansible/userdata/persistent_instance_user_data.yaml

adding history time stamps / size and command aliases

adding aliases and history config

---

ansible/userdata/default_instance_user_data.yaml
ansible/userdata/persistent_instance_user_data.yaml

adding ssh client config to disable stirct host key checking

adding ssh client config
