Financial-Times/coco-provisioner

- ansible/aws_coreos_site.yml
At least for now, as we are doing a lot of R&D work and create tonnes of
orphaned EBS volumes
> Delete ebs volumes on termination of the instances

- ansible/userdata/persistent_instance_user_data_1.yaml
- ansible/userdata/persistent_instance_user_data_2.yaml
- ansible/userdata/persistent_instance_user_data_3.yaml
Previously the the filesystem got remade on every boot, as it tried to run in interactive mode, not get a tty, and return non-zero: https://pastee.org/vak44
This change adds `-a` flag to fsck, which makes it run non-interactively and passes through on clean fs. Will also attempt to repair any faults found and if unable to will only **then** erase and make new fs.
> Attempt auto repair of fs when doing the check for fs presence

- ansible/userdata/default_instance_user_data.yaml
- ansible/userdata/persistent_instance_user_data_1.yaml
- ansible/userdata/persistent_instance_user_data_2.yaml
- ansible/userdata/persistent_instance_user_data_3.yaml
Turns out services are started sequentially so its a good idea to place
things like ssh key service near the top
> Rearranging services in userdata

- ansible/aws_coreos_site.yml
- ansible/userdata/default_instance_user_data.yaml
- ansible/userdata/persistent_instance_user_data_1.yaml
- ansible/userdata/persistent_instance_user_data_2.yaml
- ansible/userdata/persistent_instance_user_data_3.yaml
up-registry.ft.com is now behind SSL, docker should have no problems
resolving/connecting to it. Auth to follow
> Remove insecure registry option

- ansible/aws_coreos_site.yml
Adding 62.25.64.1 into Fleet security group, provides SSH access to VPN users
> Adding 62.25.64.1 into Fleet security group

- ansible/userdata/default_instance_user_data.yaml
Pull and start the deployer only on the first boot.
> Service that starts deployer honours the boot flag

- ansible/userdata/default_instance_user_data.yaml
Already removed from vault last week.
> deleting logstash crt from provisioner - no longer used

- ansible/aws_coreos_site.yml
- ansible/decom.yml
- ansible/print_userdata.yml
localhost sometimes results in Ansible running playbook on 2 hosts: localhost and 127.0.0.1
Changing the value to 127.0.0.1 will avoid this issue occurring.
When issue occurs Ansible reports the following events:
TASK [setup] *******************************************************************
ok: [localhost]
ok: [127.0.0.1]
After change Ansible reports it:
TASK [setup] *******************************************************************
ok: [127.0.0.1]
> Change hosts attribute value from localhost to 127.0.0.1

- ansible/userdata/default_instance_user_data.yaml
- ansible/userdata/persistent_instance_user_data.yaml
Tested by spinning up new 5 node cluster and confirmed that file /etc/systemd/journald.conf.d/10-override-config.conf was created automatically.
Here is console out from one of the cluster nodes after provisioning. 
core@ip-172-24-65-52 ~ $ cat /etc/systemd/journald.conf.d/10-override-config.conf
[Journal]
MaxLevelConsole=crit
Compress=fals
> Adding journald changes to provisioner

- ansible/aws_coreos_site.yml
Currently we're using standard AWS volumes, since that's the ansible
default.  These are unsuitable for our workload.  Instead, we should use
gp2 which are much better at random access workloads, such as running
databases.  Expected IOPS is also _much_ higher.
> Use gp2 volumes, which are SSD

- ansible/aws_coreos_site.yml
For EC2 instances that use persistence I have enabled instance to be
EBS-Optimized.
> Enable AWS EBS-Optimized Instances

- DEVELOPER_README.md
- README.md
- ansible/aws_coreos_site.yml
- print-userdata.sh
- provision.sh
Tag instances, ELBs, SGs etc with the appropriate environment type (eg, 'p' for prod, 't' for non-prod), rather than just tagging everything as prod.
Defaults to 'p' if no environment variable is set (as per the current behaviour).
Environment variables for test and prod clusters have been updated in LastPass.
> Add ft environment type

- ansible/userdata/persistent_instance_user_data.yaml
* see https://docs.google.com/document/d/1d21pm21vOCxNqrglCLzNj-Mr0xrnMc6gqZS0V-zse90/edit#
* haven't provisioned a new cluster with this but I have used the userdata manually in xp and it works
> Add docker host config with higher drop-in number to override old one

- README.md
- ansible/aws_coreos_site.yml
Automagically enable HTTPS listener support for ELBs in CoCo delivery clusters.
Test cluster provisioned, working as expected.
> Add ELB HTTPS support

- README.md
- decom.sh
This fixes the bug where ELBs and SGs aren't being removed properly when the decomission scripts are run.
Test cluster spun up and torn down successfully.
> Fix clusterid typo

- README.md
- ansible/decom.yml
Increase the wait period before we try to clean up the security group from 1 minute to 2 minutes.
This should prevent the SGs from failing to delete due to dependent objects - 2 mins should be plenty for the ENIs to be removed.
> Increase SG deletion wait period

- README.md
- ansible/aws_coreos_site.yml
If environment_type is production, automagically enable termination protection.  
Otherwise leave it turned off, like we currently do.
> Auto termination protection

- Dockerfile
- README.md
- ansible/decom.yml
The decomissioning playbook was still using Konstructor v1, which has been disabled, so none of our DNS records were getting removed when clusters were decomissioned.
Now updated to use Konstructor v2, and also uses Ansible's URI method instead of `curl`ing. Minor Ansible version bump to accomodate this.
> Fix DNS decomissioning

- README.md
- ansible/userdata/default_instance_user_data.yaml
- ansible/userdata/persistent_instance_user_data.yaml
* automating the masking of the update-engine
* part of the new coreos upgrade process, see https://github.com/Financial-Times/coreos-upgrade/pull/2
* built a cluster with this, works, I can unmask the service and start it:
```
~ $ sudo systemctl status update-engine
● update-engine.service
Loaded: masked (/dev/null; bad)
Active: failed (Result: exit-code) since Mon 2016-10-10 07:40:18 UTC; 3min 28s ago
~ $ sudo systemctl unmask update-engine
Removed symlink /etc/systemd/system/update-engine.service.
~ $ sudo systemctl status update-engine
● update-engine.service - Update Engine
Loaded: loaded (/usr/lib64/systemd/system/update-engine.service; disabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Mon 2016-10-10 07:40:18 UTC; 3min 42s ago
~ $ sudo systemctl start …
```
> Mask update engine

- README.md
- ansible/decom.yml
Automatically raise CRs when deleting DNS records via Konstructor.
Currently uses my own email address due to limitations in Salesforce - have requested a service account to be set up so that we can use a group email instead, but that might take a week or longer.
> Add Konstructor email for DNS changes

- README.md
Pull and run the latest stable image by default.
Saves us having to remember to update the image version in the docs every time we make a change.
> Updating readme to pull & run latest image

- ansible/aws_coreos_site.yml
Whitelist now allows access when connected to the US VPN.
Also includes fix for provisioner failing to correctly provide AZs for a region - now hard-coded to eu-west-1[a|b|c] or us-east-1[a|c|d].
> Add US VPN IP

- ansible/userdata/default_instance_user_data.yaml
- ansible/userdata/persistent_instance_user_data.yaml
Disables journald's default rate limits for new clusters.
> Disabling journald rate limiting

- ansible/decom.yml
Sometimes the DNS deletion steps fail when decommissioning, if the cluster is instantly deleted (when testing) and the services haven't created the DNS records yet, or when the endpoint times out.
Ignore the errors and continue so we don't have to go back and manually tidy up ELBs and SGs.
> Ignore DNS deletion failures

- ansible/aws_coreos_site.yml
Because we are reusing our VPCs and Subnets for the neo4j clusters, anisible attempts to remove the custom subnets. We are fairly certain our VPCs and subnets will always exists, so we can remove the logic and hard code the ids of the VPCs and the subnets
> remove VPC logic
